### ISSUE TITLE
Unexpected type for eventdetection_version

### ISSUE THREAD

**Issue by davidcfritz** [mateidavid/fast5#9]
I've installed hdf5 1.8.16 (32-bit) and built f5dump using MSVS 2015, 32-bit console application. When I run it on any ONT fast5 file I get the following written to the console:

file_version=1
sampling_rate=3012
have_sequences_group=0
have_raw_samples=0
have_eventdetection_group=1
HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 0:
  #000: C:\autotest\HDF518ReleaseRWDITAR\src\H5A.c line 642 in H5Aread(): unable to read attribute
    major: Attribute
    minor: Read failed
  #001: C:\autotest\HDF518ReleaseRWDITAR\src\H5Aint.c line 641 in H5A_read(): unable to convert between src and dst datatypes
    major: Attribute
    minor: Feature is unsupported
  #002: C:\autotest\HDF518ReleaseRWDITAR\src\H5T.c line 4548 in H5T_path_find(): no appropriate function for conversion path
    major: Datatype
    minor: Unable to initialize object
hdf5 error: /Analyses/EventDetection_000/version: error in H5Aread

Any idea what I've may have done wrong?

**Comment by davidcfritz** [comment]
Additionally, I did a 64-bit build and got exactly the same results.

The error occurs in the 5th call to H5Aread() on line 532 of hdf5_tools.hpp.

**Comment by mateidavid** [comment]
I've never built or tested it on Windows, but I'll try to diagnose this here.

Can you tell from the stack dump what attribute is being read? If not- Looking at `f5dump.cpp`, the first call after printing `have_eventdetection_group=1` is on L79, to `eventdetection_version()`. In turn, that one tries to read `/Analyses/EventDetection_000/version`. Can you run `h5dump -a /Analyses/EventDetection_000/version <file>` on one of your files and print the output here?

**Comment by davidcfritz** [comment]
Here it is:

 

C:\data\reads\downloads\pass>h5dump -a /Analyses/EventDetection_000/version TEST12345_ch1_file19.fast5

HDF5 "TEST12345_ch1_file19.fast5" {

ATTRIBUTE "version" {

   DATATYPE  H5T_IEEE_F64LE

   DATASPACE  SCALAR

   DATA {

   (0): 1

   }

}

}

 

Thanks!

**Comment by davidcfritz** [comment]
How can I get you the fast5 file? I can’t seem to attach it here.

**Comment by mateidavid** [comment]
Scalar 64bit float... great! No wonder it crashes, it's expecting a string. Is this a new R9 file?

You have my email in `git log`, just send me a file there. Hopefully you can find one <10MB or so.

**Comment by mateidavid** [comment]
I edited the title. The main reason for such issues is the ONT keeps changing the internal fast5 format without providing a formal spec.

**Comment by davidcfritz** [comment]
My test case is a new file from the latest MINION kit, generated just a few days ago.
[TEST12345_ch1_file19.zip](https://github.com/mateidavid/fast5/files/176980/TEST12345_ch1_file19.zip)

**Comment by davidcfritz** [comment]
Frankly, a string makes a lot more sense for the version. But, I suppose ONT has their reasons for using a float.

**Comment by mateidavid** [comment]
Did you see `/Copyright` and `/Description`? Based on those, I'm not sure how to proceed with this issue: Copyright is certainly problematic, perhaps we should take the file down? Also, Description suggests this is not real data, and that it should not be used for software development, which is what we're doing here. Do you have any files not labelled "test data" and not copyrighted?

**Comment by davidcfritz** [comment]
I have not been able to dump the file, so I did not see these. 

 

Let me check with ONT support and get a read on this. The file I gave you is from ONT to test their Metrichor interface. I seriously doubt there is anything truly confidential in the file. The data is canned and legitimate as the aligned calls that resulted have been verified.

 

In the meantime, it won’t hurt to remove the file from the site.

**Comment by davidcfritz** [comment]
Here is a file I generated myself. It may only have events but it shows the same version problem.
[InteliScout5_0311151944.zip](https://github.com/mateidavid/fast5/files/178563/InteliScout5_0311151944.zip)

**Comment by mateidavid** [comment]
This one doesn't have an eventdetection group, which causes `fast5::File::is_valid_file()` to return `false`, so `f5dump` doesn't try to read it any further. I'm not convinced that's a good file to work on either.

Re: the OP problem- Older fast5 files had a string as ED version, and now the files you see have a 64-bit float. It may well be the case that one of the other fields in that file would allow us to detect this situation, specifically, to anticipate what data type to expect as ED version. E.g., perhaps `chimaera version` or `dragonet version`. However, since we don't have such a spec from ONT, it would all be guessing. Say we were to guess `chimaera version` would be relevant, and I added a branch such as: if `chimaera version >= 1.16.8` (which is what your original file showed) then read a float, else read a string. If I do that and `chimaera version` is in fact not relevant (meaning our guess was wrong), I end up breaking `fast5` for others who have that same `chimaera version` but with a string ED version.

In part motivated by the OP Issue, I opened an issue with ONT Support asking them for a spec, but so far they only provided this general reference: https://protocols.nanoporetech.com/technical_documents/metrichor-technical-docume/v/metd_5000_v1_reva_29feb201/read-fast5-file-from-th . I would prefer to wait with this Issue until we hear from one of their technical people.

**Comment by mateidavid** [comment]
No word yet.

**Comment by davidcfritz** [comment]
I changed the code myself and got it to work flawlessly on every fast5 file I have. Of course, that doesn't help with backward compatibility.

There are a couple of attributes that should always be 1 so they have been removed to reduce file size.

I also complained to the US ONT rep about the poor documentation.

Thanks,

David

**Comment by mateidavid** [comment]
The ONT's reply on this issue was something along the line that they have the necessary documentation, but not in a presentable form.

In the meantime, I've seen recently generated R9 files where the type of `/Analyses/EventDetection_000/version` is (again?) `H5T_STRING`. Because of this, I will close this issue for now.
